import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import PageContainer from "@/components/PageContainer";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} antialiased flex overflow-x-hidden w-screen h-screen bg-neutral-100 text-gray-500`}
			>
				<Sidebar />
				<PageContainer>{children}</PageContainer>
			</body>
		</html>
	);
}
